# Encoding: utf-8
name 'pythonstack'
maintainer 'Rackspace'
maintainer_email 'rackspace-cookbooks@rackspace.com'
license 'Apache 2.0'
description 'Installs/Configures pythonstack'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '2.0.1'

depends 'apache2'
depends 'application'
depends 'application_python'
depends 'apt'
depends 'build-essential'
depends 'chef-sugar'
depends 'git'
depends 'mysql' # needed in the application_python recipe
depends 'nginx'
depends 'platformstack', '>= 3.1.4'
depends 'python'
depends 'rackspace_gluster'
depends 'stack_commons', '>= 0.0.49'
depends 'uwsgi'
depends 'yum'
depends 'yum-epel'
depends 'yum-ius'
